# pylint: disable = too-many-lines
"""
This module defines the DetailUtility class for the Sentinel.
This class defines the properties of i buttons when an expanded element is clicked
"""


class DetailUtility:
    """
    This class defines the properties of i buttons when an expanded element is clicked
    """

    def __init__(self):
        raise RuntimeError("This class cannot be instantiated")
    
    @staticmethod
    def get_dictionary(name):
        """
        Get the expanded element dictionary

        Returns:
            dict: Expanded element dictionary
        """
        expanded_element_dict = {
            "IC-E-102 A~D": {
                "Diagram": {
                    "path": "assets/ic_e_102.png",
                    "scale_x": 1000,
                    "scale_y": 650,
                    "position_x": 0,
                    "position_y": 0,
                    "db_name": "diagram",
                    "is_pipeline": False,
                    "name": "Diagram",
                    "image_folder": None,
                },
                "info 1": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -420,
                    "position_y": 30,
                    "db_name": "ice102_a",
                    "is_pipeline": False,
                    "name": "IC-E-102 A",
                    "image_folder": None,
                },
                "info 2": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -200,
                    "position_y": 30,
                    "db_name": "ice102_b",
                    "is_pipeline": False,
                    "name": "IC-E-102 B",
                    "image_folder": None,
                },
                "info 3": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 10,
                    "position_y": 30,
                    "db_name": "ice102_c",
                    "is_pipeline": False,
                    "name": "IC-E-102 C",
                    "image_folder": None,
                },
                "info 4": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 230,
                    "position_y": 30,
                    "db_name": "ice102_d",
                    "is_pipeline": False,
                    "name": "IC-E-102 D",
                    "image_folder": None,
                },
                "pipeline_cdu_a": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -353,
                    "position_y": -50,
                    "db_name": "pipeline_cdu_a",
                    "is_pipeline": True,
                    "image_folder": "ADUtoHE",
                    "name": "Pipeline(ADU to IC-E-102 A)",
                },
                "pipeline_cdu_b": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -317,
                    "position_y": -50,
                    "db_name": "pipeline_cdu_b",
                    "is_pipeline": True,
                    "image_folder": "ADUtoHE",
                    "name": "Pipeline(ADU to IC-E-102 B)",
                },
                "pipeline_cdu_c": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 79,
                    "position_y": -50,
                    "db_name": "pipeline_cdu_c",
                    "is_pipeline": True,
                    "image_folder": "ADUtoHE",
                    "name": "Pipeline(ADU to IC-E-102 C)",
                },
                "pipeline_cdu_d": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 115,
                    "position_y": -50,
                    "db_name": "pipeline_cdu_d",
                    "is_pipeline": True,
                    "image_folder": "ADUtoHE",
                    "name": "Pipeline(ADU to IC-E-102 D)",
                },
            },
            "IC-E-161 A~H": {
                "Diagram": {
                    "path": "assets/ic_e_161.png",
                    "scale_x": 1100,
                    "scale_y": 700,
                    "position_x": 0,
                    "position_y": 0,
                    "name": "Diagram",
                    "db_name": "diagram",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 1": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -345,
                    "position_y": -35,
                    "name": "IC-E-161 A",
                    "db_name": "ice161_a",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 2": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -240,
                    "position_y": -35,
                    "name": "IC-E-161 B",
                    "db_name": "ice161_b",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 3": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -173,
                    "position_y": -35,
                    "name": "IC-E-161 C",
                    "db_name": "ice161_c",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 4": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -67,
                    "position_y": -35,
                    "name": "IC-E-161 D",
                    "db_name": "ice161_d",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 5": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -4,
                    "position_y": -35,
                    "name": "IC-E-161 E",
                    "db_name": "ice161_e",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 6": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 90,
                    "position_y": -35,
                    "name": "IC-E-161 F",
                    "db_name": "ice161_f",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 7": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 160,
                    "position_y": -35,
                    "name": "IC-E-161 G",
                    "db_name": "ice161_g",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "info 8": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 260,
                    "position_y": -35,
                    "name": "IC-E-161 H",
                    "db_name": "ice161_h",
                    "is_pipeline": False,
                    "image_folder": None,
                },
                "pipeline_ice102_a": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -315,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_a",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 A to IC-E-161 A)",
                },
                "pipeline_ice102_b": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -210,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_b",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 A to IC-E-161 B)",
                },
                "pipeline_ice102_c": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -145,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_c",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 B to IC-E-161 C)",
                },
                "pipeline_ice102_d": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -40,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_d",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 B to IC-E-161 D)",
                },
                "pipeline_ice102_e": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 15,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_e",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 C to IC-E-161 E)",
                },
                "pipeline_ice102_f": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 120,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_f",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 C to IC-E-161 F)",
                },
                "pipeline_ice102_g": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 175,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_g",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 D to IC-E-161 G)",
                },
                "pipeline_ice102_h": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 280,
                    "position_y": -80,
                    "db_name": "pipeline_ice102_h",
                    "is_pipeline": True,
                    "image_folder": "HEtoCooler",
                    "name": "Pipeline(IC-E-102 D to IC-E-161 H)",
                },
            },
            "IC-E-162 A~P": {
                "Diagram": {
                    "path": "assets/ic_e_162.png",
                    "scale_x": 1500,
                    "scale_y": 700,
                    "position_x": 0,
                    "position_y": 0,
                    "db_name": "diagram",
                    "is_pipeline": False,
                    "name": "Diagram",
                    "image_folder": None,
                },
                "info 1": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -593,
                    "position_y": 100,
                    "db_name": "ice162_a",
                    "is_pipeline": False,
                    "name": "IC-E-162 A",
                    "image_folder": None,
                },
                "info 2": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -513,
                    "position_y": 100,
                    "db_name": "ice162_b",
                    "is_pipeline": False,
                    "name": "IC-E-162 B",
                    "image_folder": None,
                },
                "info 3": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -434,
                    "position_y": 100,
                    "db_name": "ice162_c",
                    "is_pipeline": False,
                    "name": "IC-E-162 C",
                    "image_folder": None,
                },
                "info 4": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -356,
                    "position_y": 100,
                    "db_name": "ice162_d",
                    "is_pipeline": False,
                    "name": "IC-E-162 D",
                    "image_folder": None,
                },
                "info 5": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -273,
                    "position_y": 100,
                    "db_name": "ice162_e",
                    "is_pipeline": False,
                    "name": "IC-E-162 E",
                    "image_folder": None,
                },
                "info 6": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -194,
                    "position_y": 100,
                    "db_name": "ice162_f",
                    "is_pipeline": False,
                    "name": "IC-E-162 F",
                    "image_folder": None,
                },
                "info 7": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -115,
                    "position_y": 100,
                    "db_name": "ice162_g",
                    "is_pipeline": False,
                    "name": "IC-E-162 G",
                    "image_folder": None,
                },
                "info 8": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -37,
                    "position_y": 100,
                    "db_name": "ice162_h",
                    "is_pipeline": False,
                    "name": "IC-E-162 H",
                    "image_folder": None,
                },
                "info 9": {
                    "path": "assets/inhistory_report_widget_layoutfo.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 35,
                    "position_y": 100,
                    "db_name": "ice162_i",
                    "is_pipeline": False,
                    "name": "IC-E-162 I",
                    "image_folder": None,
                },
                "info 10": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 115,
                    "position_y": 100,
                    "db_name": "ice162_j",
                    "is_pipeline": False,
                    "name": "IC-E-162 J",
                    "image_folder": None,
                },
                "info 11": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 194,
                    "position_y": 100,
                    "db_name": "ice162_k",
                    "is_pipeline": False,
                    "name": "IC-E-162 K",
                    "image_folder": None,
                },
                "info 12": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 273,
                    "position_y": 100,
                    "db_name": "ice162_l",
                    "is_pipeline": False,
                    "name": "IC-E-162 L",
                    "image_folder": None,
                },
                "info 13": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 356,
                    "position_y": 100,
                    "db_name": "ice162_m",
                    "is_pipeline": False,
                    "name": "IC-E-162 M",
                    "image_folder": None,
                },
                "info 14": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 434,
                    "position_y": 100,
                    "db_name": "ice162_n",
                    "is_pipeline": False,
                    "name": "IC-E-162 N",
                    "image_folder": None,
                },
                "info 15": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 512,
                    "position_y": 100,
                    "db_name": "ice162_o",
                    "is_pipeline": False,
                    "name": "IC-E-162 O",
                    "image_folder": None,
                },
                "info 16": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 591,
                    "position_y": 100,
                    "db_name": "ice162_p",
                    "is_pipeline": False,
                    "name": "IC-E-162 P",
                    "image_folder": None,
                },
                "pipeline_icv112_a": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -593,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_a",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 A)",
                },
                "pipeline_icv112_b": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -513,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_b",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 B)",
                },
                "pipeline_icv112_c": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -434,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_c",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 C)",
                },
                "pipeline_icv112_d": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -356,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_d",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 D)",
                },
                "pipeline_icv112_e": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -273,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_e",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 E)",
                },
                "pipeline_icv112_f": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -194,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_f",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 F)",
                },
                "pipeline_icv112_g": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -115,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_g",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 G)",
                },
                "pipeline_icv112_h": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": -37,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_h",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 H)",
                },
                "pipeline_icv112_i": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 35,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_i",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 I)",
                },
                "pipeline_icv112_j": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 115,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_j",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 J)",
                },
                "pipeline_icv112_k": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 194,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_k",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 K)",
                },
                "pipeline_icv112_l": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 273,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_l",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 L)",
                },
                "pipeline_icv112_m": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 356,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_m",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 M)",
                },
                "pipeline_icv112_n": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 434,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_n",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 N)",
                },
                "pipeline_icv112_o": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 512,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_o",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 O)",
                },
                "pipeline_icv112_p": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 591,
                    "position_y": 0,
                    "db_name": "pipeline_icv112_p",
                    "is_pipeline": True,
                    "image_folder": "RD1toCooler2",
                    "name": "Pipeline(IC-V-112 to IC-E-162 P)",
                },
            },
            "IC-E-126 A~D": {
                "Diagram": {
                    "path": "assets/ic_e_126.png",
                    "scale_x": 700,
                    "scale_y": 780,
                    "position_x": 0,
                    "position_y": 0,
                    "db_name": "ice102_a-d",
                    "is_pipeline": False,
                    "name": "Diagram",
                    "image_folder": None,
                },
                "info 1": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 50,
                    "position_y": 65,
                    "db_name": "ice126_a",
                    "is_pipeline": False,
                    "name": "IC-E-126 A",
                    "image_folder": None,
                },
                "info 2": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 50,
                    "position_y": -35,
                    "db_name": "ice126_b",
                    "is_pipeline": False,
                    "name": "IC-E-126 B",
                    "image_folder": None,
                },
                "info 3": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 265,
                    "position_y": 65,
                    "db_name": "ice126_c",
                    "is_pipeline": False,
                    "name": "IC-E-126 C",
                    "image_folder": None,
                },
                "info 4": {
                    "path": "assets/info.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 265,
                    "position_y": -35,
                    "db_name": "ice126_d",
                    "is_pipeline": False,
                    "name": "IC-E-126 D",
                    "image_folder": None,
                },
                "pipeline_ice162_a_b": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 65,
                    "position_y": -150,
                    "db_name": "pipeline_ice162_a_b",
                    "is_pipeline": True,
                    "image_folder": "Cooler2toHE2",
                    "name": "Pipeline(IC-E-162 to IC-E-126 A/B)",
                },
                "pipeline_ice162_c_d": {
                    "path": "assets/info_pipe.png",
                    "scale_x": 20,
                    "scale_y": 20,
                    "position_x": 200,
                    "position_y": -150,
                    "db_name": "pipeline_ice162_c_d",
                    "is_pipeline": True,
                    "image_folder": "Cooler2toHE2",
                    "name": "Pipeline(IC-E-162 to IC-E-126 C/D)",
                },
            },
        }
        
        return expanded_element_dict[name]
