# Form implementation generated from reading ui file 'crude_blend_table.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets, QtGui
from src.utils.year_month_table_combined.tab_button import TabButtonBar
from src.utils.year_month_table_combined.light_column_frozen_table import FrozenTable
from src.utils.core_utility_functions import get_year_range, month_short_name, resource_path
from src.utils.tables.pagination import PaginationWidget

class TabTableCombined(object):
    def __init__(self, column_names=None,data=None, frozen_columns: int = 1, parent=None,
                 show_date_navigation: bool = True, show_pagination: bool = True):
        if column_names is None:
            self.column_names = ["DemoC1", "DemoC2", "DemoC3", "DemoC4", "DemoC5", "DemoC6", "DemoC7", "DemoC8", "DemoC9"]
        else:
            self.column_names = column_names
        if data is None:
            self.data = [()]
        else:
            self.data = data

        self.frozen_column = frozen_columns

        # Tables whose data is not organised by month (the general crude
        # library) opt out of the year/month row entirely. Building it and
        # deleting it afterwards is not enough: deleteLater() only runs when
        # the event loop gets back to it, so the row stayed on screen whenever
        # the application was busy.
        self.show_date_navigation = show_date_navigation
        self.show_pagination = show_pagination

        # Add month tabs
        self.months_short_names = month_short_name()

        self.min_column_width = 120
        self.max_column_width = 400

    def setupUi(self, Form):

        # create the main vertical layout
        self.main_vlayout = QtWidgets.QVBoxLayout(Form)
        self.main_vlayout.setSpacing(0)

        # widget to contain the year combo box and the month tabs
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget.setMinimumSize(QtCore.QSize(16777215, 35))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)

        # Only created when this table is browsed by month
        self.year_combo_box = None
        self.scrollArea = None
        self.scrollAreaWidgetContents = None
        self.tabBar = None
        self.refresh_button = None
        self.line = None
        self.pagination_widget = None

        if self.show_date_navigation:
            self._setup_date_navigation(Form)

        self.main_vlayout.addWidget(self.widget)

        if self.show_date_navigation:
            self.line = QtWidgets.QFrame(parent=Form)
            self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
            self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
            self.main_vlayout.addWidget(self.line)

        self.table_widget = self.create_frozen_table(column_names=self.column_names, data=self.data, frozen_columns=self.frozen_column)
        self.main_vlayout.addWidget(self.table_widget)

        if self.show_pagination:
            self.pagination_widget = PaginationWidget(parent=Form)
            self.main_vlayout.addWidget(self.pagination_widget)

    def _setup_date_navigation(self, Form):
        """Year combo box, month tabs and refresh button, in the header row."""

        # Create a QComboBox for the year
        self.year_combo_box = QtWidgets.QComboBox(parent=self.widget)
        self.year_combo_box.setProperty("compact", True)
        self.horizontalLayout.addWidget(self.year_combo_box)
        # add year from 2025 to 2050
        year_range = get_year_range()
        for year in year_range:
            self.year_combo_box.addItem(str(year))

        # set the self.year_combo_box to the current year
        current_year = QtCore.QDate.currentDate().year()
        self.year_combo_box.setCurrentText(str(current_year))

        # limit visible items in the dropdown
        self.year_combo_box.setMaxVisibleItems(10)  # or whatever number you prefer

        # enforce via stylesheet if you notice the list is still too tall
        self.year_combo_box.setStyleSheet("QComboBox { combobox-popup: 0; }")

        # month tab buttons
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)

        # The months are a single row of buttons, so there is nothing to scroll
        # to vertically. Left on "as needed", a viewport a pixel shorter than
        # the buttons pops a vertical scrollbar next to the tabs, and that
        # scrollbar then eats the width the tabs need and pushes Dec out of view.
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.tabBar = TabButtonBar(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.tabBar)

        for month in self.months_short_names:
            self.tabBar.addTab(month)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        # Stretch, so the tabs keep their width instead of being squeezed by the
        # trailing spacer of the toolbars the subclasses add to this row.
        self.horizontalLayout.addWidget(self.scrollArea, 1)

        # Size the row to what the tabs actually need, plus room for the
        # horizontal scrollbar that shows when the window is too narrow for all
        # twelve months. A fixed 35px row is a pixel or two short of the styled
        # buttons, which is what made the scrollbars appear in the first place.
        row_height = max(
            35,
            self.tabBar.sizeHint().height()
            + self.scrollArea.horizontalScrollBar().sizeHint().height(),
        )
        self.widget.setMaximumSize(QtCore.QSize(16777215, row_height))
        self.widget.setMinimumSize(QtCore.QSize(16777215, row_height))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, row_height))

        # add a refresh button
        self.refresh_button = QtWidgets.QToolButton(parent=self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("assets/refresh.png")),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.refresh_button.setIcon(icon)
        self.refresh_button.setAutoRaise(True)
        self.refresh_button.setIconSize(QtCore.QSize(20, 20))
        self.refresh_button.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.refresh_button.setToolTip("Refresh")
        self.horizontalLayout.addWidget(self.refresh_button)

    def create_frozen_table(self,column_names=None, data=None, frozen_columns: int = 1):
        
        table_widget = FrozenTable(column_names=column_names, data=data, frozen_columns=frozen_columns,
         min_column_width=self.min_column_width, max_column_width=self.max_column_width,
            parent=None
        )
        return table_widget
    
        
class TabTableWidget(QtWidgets.QWidget):
    """
    QWidget wrapper for the generated Ui_Form.

    Usage:
        widget = TabTableWidget(parent=my_parent, column_names=my_columns)
        layout.addWidget(widget)
    """
    def __init__(self, parent=None, column_names=None, data=None, frozen_columns: int = 1,
                 show_date_navigation: bool = True, show_pagination: bool = True, **kwargs):
        super().__init__(parent)

        # Pass column_names into TabTableCombined
        self.combined_ui = TabTableCombined(column_names=column_names,data=data,frozen_columns=frozen_columns, parent=self,
                                            show_date_navigation=show_date_navigation, show_pagination=show_pagination)

        # Build the UI with those column names
        # self.combined_ui.setupUi(self)


def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)

    w = QtWidgets.QMainWindow()
    w.setWindowTitle("Frozen FIRST Column - Polished UI")
    widget = TabTableWidget()
    w.setCentralWidget(widget)
    w.resize(1200, 700)
    w.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
